apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-react-frontend
  description: A React frontend application
  labels:
    type: frontend
  links:
    - url: http://192.168.1.3:3001/
      title: frontend
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: suriyags

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-flask-backend
  description: A Flask backend service
  labels:
    type: backend
  links:
    - url: http://192.168.1.3:8091/get_device
      title: backend
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: suriyags

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: my-system
  description: The system that contains my frontend and backend services
spec:
  lifecycle: production
  owner: suriyags
  components:
    - ref: my-react-frontend
    - ref: my-flask-backend
