apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-react-flask-app
  description: |
    A simple React frontend and Python Flask backend application.
  links:
    - title: React Frontend
      url: http://localhost:3001
    - title: Flask Backend
      url: http://localhost:8090
    - title: GitHub Repository
      url: https://github.com/suriyags/backstage1903/tree/master
  annotations:
    github.com/project-slug: suriyags/backstage1903
    backstage.io/techdocs-ref: dir:.
spec:
  type: application
  owner: suriyags
  lifecycle: experimental
