apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-react-frontend
  description: A React frontend application
  labels:
    type: frontend
  annotations:
    backstage.io/tech-docs-like: 'true'
    backstage.io/frontend-url: 'http://192.168.1.3:3001/'
  links:
    - url: http://192.168.1.3:3001/
      title: Frontend Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: http://192.168.1.3:3001/docs
      title: Frontend Documentation
      icon: documentation
      type: documentation
spec:
  type: service
  lifecycle: production
  owner: suriyags

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-flask-backend
  description: A Flask backend service
  labels:
    type: backend
  annotations:
    backstage.io/view-url: 'http://192.168.1.3:8091'
    backstage.io/managed-by-location: url:https://github.com/suriyags/backstage1903/blob/master/app-config.yaml
  links:
    - url: http://192.168.1.3:8091/get_device
      title: Backend API
      icon: api
      type: api-docs
    - url: http://192.168.1.3:8091/docs
      title: Backend Documentation
      icon: documentation
      type: documentation
spec:
  type: service
  lifecycle: production
  owner: suriyags

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: my-system
  description: The system that contains my frontend and backend services
  annotations:
    backstage.io/system-architect: 'suriyags'
spec:
  lifecycle: production
  owner: suriyags
  components:
    - ref: my-react-frontend
    - ref: my-flask-backend
