apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-react-frontend
  description: A React frontend application
  labels:
    type: frontend
spec:
  type: service
  lifecycle: production
  owner: default/suriyags

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-flask-backend
  description: A Flask backend service
  labels:
    type: backend
spec:
  type: service
  lifecycle: production
  owner: default/suriyags

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: my-system
  description: The system that contains my frontend and backend services
spec:
  lifecycle: production
  owner: default/suriyags
  components:
    - my-react-frontend
    - my-flask-backend
